old_sound_rabbit_mq:
    connections:
        default:
            url:  '%rabbit_mq.url%'
            lazy: false

            #due to highload set this parameter to 15 secs
            connection_timeout: 15
            read_write_timeout: 10

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

    producers:
        passport_check:
            connection:       default
            exchange_options: { name: 'passport_check', type: direct }
            queue_options:
                name: 'passport_check'
                arguments:
                    x-max-priority: ['I', 255]
            class: App\AMQP\Producer\PassportCheckProducer

        passport_check_delayed:
            connection:       default
            exchange_options: { name: 'passport_check_delayed', type: direct }
            queue_options:
                name: 'passport_check_delayed'
                arguments:
                    x-dead-letter-exchange: ['S', 'passport_check']
                    x-max-priority:         ['I', 255]
            class: App\AMQP\Producer\PassportCheckDelayedProducer

    consumers:
        passport_check:
            connection:       default
            exchange_options: { name: 'passport_check', type: direct }
            queue_options:
                name: 'passport_check'
                arguments:
                    x-max-priority: ['I', 255]
            callback:    App\AMQP\Consumer\PassportCheckConsumer
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
            graceful_max_execution:
                timeout: 1800
